apiVersion: tensorstack.io/v1beta1
kind: ClockedPipeline
metadata:
  name: every-minute-cron
spec:
  description: "every-minute-cron"
  enabled: true
  maxHistory: 10
  trigger:
    cronSchedule:
      cron: 1 * * * * *
  workflow:
    spec:
      entrypoint: whalesay
      arguments:
        parameters:
        - name: message
          value: hello world
      templates:
      - name: whalesay
        inputs:
          parameters:
          - name: message
        container:
          image: docker/whalesay
          command: [cowsay]
          args: ["{{inputs.parameters.message}}"]
