apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"oauth2-proxy"},"name":"oauth2-proxy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"oauth2-proxy"}},"template":{"metadata":{"labels":{"k8s-app":"oauth2-proxy"}},"spec":{"containers":[{"args":["--provider=oidc","--client-id=oauth2_proxy-n04","--client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0","--cookie-secure=true","--email-domain=*","--oidc-issuer-url=https://dex.c.kube.tensorstack.net","--redirect-url=https://proxy.n.kube.tensorstack.net/oauth2/callback","--upstream=http://http-svc/","--http-address=0.0.0.0:4180","--pass-authorization-header=true","--pass-basic-auth=true","--pass-access-token=true","--set-authorization-header=true","--scope=openid profile email groups audience:server:client_id:gangway-n04"],"env":[{"name":"OAUTH2_PROXY_COOKIE_SECRET","value":"9PYlltdMtYUaK3VBXMhjdA=="}],"image":"quay.io/pusher/oauth2_proxy:v3.2.0","imagePullPolicy":"Always","name":"oauth2-proxy","ports":[{"containerPort":4180,"protocol":"TCP"}]}]}}}}
  creationTimestamp: "2019-05-08T02:52:04Z"
  generation: 11
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
  resourceVersion: "161382980"
  selfLink: /apis/apps/v1/namespaces/default/deployments/oauth2-proxy
  uid: 42d64ea8-713c-11e9-bb49-70e14c6834dc
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --client-id=oauth2_proxy-n04
        - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
        - --cookie-secure=true
        - --email-domain=*
        - --oidc-issuer-url=https://dex.c.kube.tensorstack.net
        - --redirect-url=https://proxy.n.kube.tensorstack.net/oauth2/callback
        - --upstream=http://istio-ingressgateway.istio-system.svc.cluster.local/
        - --http-address=0.0.0.0:4180
        - --pass-authorization-header=true
        - --pass-basic-auth=true
        - --pass-access-token=true
        - --set-authorization-header=true
        - --scope=openid profile email groups audience:server:client_id:gangway-n04
        - --skip-provider-button=true
        - --extra-jwt-issuers=https://dex.c.kube.tensorstack.net=gangway-n04
        - --skip-jwt-bearer-tokens=true
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: 9PYlltdMtYUaK3VBXMhjdA==
        image: quay.io/pusher/oauth2_proxy:v4.0.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30