apiVersion: v1
kind: Secret
metadata:
  name: minio-access-keys
  namespace: t9k-czx
type: Opaque
data:
  # Base64 encoded string: "tensorstack"
  username: dGVuc29yc3RhY2s=
  # Base64 encoded string: "tensorstack"
  password: dGVuc29yc3RhY2s=
